const { applyMove, getWinner } = require('./gameLogic');
const { sanitizeName, normalizeCode, validToken } = require('./validators');
const ok = (message, data = {}) => ({ success: true, message, data });
const fail = (message, errorCode) => ({ success: false, message, errorCode });
module.exports = function register(io, manager) {
  const emitRoom = room => io.to(room.roomCode).emit('room-updated', ok('', manager.public(room)));
  const reject = (socket, event, message, code) => socket.emit(event, fail(message, code));
  io.on('connection', socket => {
    socket.on('create-room', payload => { const playerName = sanitizeName(payload?.playerName); if (!playerName) return reject(socket,'room-error','ชื่อต้องมี 1-20 ตัวอักษร','INVALID_NAME'); const {room,token}=manager.create(playerName,socket.id); socket.join(room.roomCode); socket.emit('room-created',ok('สร้างห้องแล้ว',{room:manager.public(room),playerToken:token})); console.log('create-room',room.roomCode); });
    socket.on('join-room', payload => { try { const playerName=sanitizeName(payload?.playerName), code=normalizeCode(payload?.roomCode); if(!playerName||!code) return reject(socket,'room-error','ชื่อหรือรหัสห้องไม่ถูกต้อง','INVALID_INPUT'); const {room,token}=manager.join(code,playerName,socket.id); socket.join(code); socket.emit('room-joined',ok('เข้าห้องแล้ว',{room:manager.public(room),playerToken:token})); io.to(code).emit('game-started',ok('เริ่มเกม',manager.public(room))); console.log('join-room',code); } catch(e){ reject(socket,'room-error',e.message,e.code); } });
    socket.on('reconnect-room', payload => { const code=normalizeCode(payload?.roomCode); if(!code||!validToken(payload?.playerToken)) return reject(socket,'room-error','ข้อมูลเชื่อมต่อไม่ถูกต้อง','INVALID_RECONNECT'); const found=manager.reconnect(code,payload.playerToken,socket.id); if(!found) return reject(socket,'room-error','ไม่สามารถกลับเข้าห้องได้','RECONNECT_FAILED'); socket.join(code); socket.emit('player-reconnected',ok('เชื่อมต่อกลับแล้ว',{room:manager.public(found.room)})); emitRoom(found.room); });
    let lastMove=0;
    socket.on('make-move', payload => { const now=Date.now(); if(now-lastMove<250) return reject(socket,'invalid-move','ส่งคำสั่งเร็วเกินไป','RATE_LIMITED'); lastMove=now; const code=normalizeCode(payload?.roomCode), room=manager.rooms.get(code), player=manager.player(room,socket.id); if(!room||!player) return reject(socket,'invalid-move','ไม่พบผู้เล่นหรือห้อง','UNAUTHORIZED'); if(room.status!=='playing') return reject(socket,'invalid-move','เกมยังไม่เริ่มหรือจบแล้ว','GAME_NOT_ACTIVE'); if(room.currentTurn!==player.color) return reject(socket,'invalid-move','ยังไม่ถึงตาของคุณ','WRONG_TURN'); const result=applyMove(room.board,player.color,payload?.from,payload?.to); if(!result.valid) return reject(socket,'invalid-move',result.message,'INVALID_MOVE'); room.board=result.board; const next=player.color==='black'?'white':'black'; const winner=getWinner(room.board,next); room.currentTurn=next; room.updatedAt=now; if(winner){ room.status='finished'; room.winner=winner; io.to(code).emit('game-over',ok('เกมจบ',{...manager.public(room),winner})); } else io.to(code).emit('move-accepted',ok('เดินสำเร็จ',{...manager.public(room),captured:result.captured})); console.log('make-move',code,player.color); });
    socket.on('resign-game', payload => { const room=manager.rooms.get(normalizeCode(payload?.roomCode)), player=manager.player(room,socket.id); if(!player||room.status!=='playing') return reject(socket,'room-error','ไม่สามารถยอมแพ้ได้','INVALID_RESIGN'); const winnerColor=player.color==='black'?'white':'black'; room.status='finished'; room.winner={color:winnerColor,reason:'ฝ่ายตรงข้ามยอมแพ้'}; io.to(room.roomCode).emit('game-over',ok('เกมจบ',manager.public(room))); });
    socket.on('request-rematch', payload => { const room=manager.rooms.get(normalizeCode(payload?.roomCode)), player=manager.player(room,socket.id); if(!player||room.status!=='finished') return reject(socket,'room-error','ยังขอเล่นใหม่ไม่ได้','INVALID_REMATCH'); room.rematchVotes.add(player.token); if(room.rematchVotes.size===2){ room.board=require('./gameLogic').createInitialBoard(); room.currentTurn='black'; room.status='playing'; room.winner=null; room.rematchVotes.clear(); io.to(room.roomCode).emit('rematch-started',ok('เริ่มเกมใหม่',manager.public(room))); } else emitRoom(room); });
    socket.on('leave-room', payload => { const code=normalizeCode(payload?.roomCode); socket.leave(code||''); const room=manager.remove(code,socket.id); if(room) { io.to(code).emit('game-over',ok('ผู้เล่นออกจากเกม',{...manager.public(room),winner:{color:room.players[0]?.color,reason:'ฝ่ายตรงข้ามออกจากเกม'}})); } });
    socket.on('disconnect', () => { for(const room of manager.rooms.values()){ const player=manager.player(room,socket.id); if(player){ player.connected=false; room.updatedAt=Date.now(); io.to(room.roomCode).emit('player-disconnected',ok(`${player.playerName} หลุดการเชื่อมต่อ`,manager.public(room))); break; } } });
  });
  const timer=setInterval(()=>manager.cleanup(),60_000); timer.unref();
};
